version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Rohit@8540
      MYSQL_DATABASE: fracas_scr
      MYSQL_USER: root
      MYSQL_PASSWORD: Rohit@8540
    ports:
      - "3306:3306"

  springboot-app:
    build: .
    ports:
      - "8541:8541"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fracas_scr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rohit@8540
